### PR TITLE
added a card to the project and deleted the Helloword component

### PR DESCRIPTION
**Pull request by XianBarbera**

### CODE REVIEW

**Review by ClaudioIrianni — APPROVED** [review]
Old

**Review by ClaudioIrianni — APPROVED** [review]
Button change

**Review by ClaudioIrianni — APPROVED** [review]
HelloWorld deleted.

**Review by ClaudioIrianni — APPROVED** [review]
Cambios hechos.

**Review by PawFV — APPROVED** [review]

**Pull request merged**
